import ConversationController from '@/actions/App/Http/Controllers/Api/ConversationController';
import ConversationMessageController from '@/actions/App/Http/Controllers/Api/ConversationMessageController';

import type {
    Conversation,
    ConversationLevel,
    ConversationWithMessages,
    SendMessageResponse,
} from '@/types/conversation';

export class ApiError extends Error {
    status: number;

    constructor(message: string, status: number) {
        super(message);
        this.name = 'ApiError';
        this.status = status;
    }
}

/**
 * Get the CSRF token generated by Laravel's /sanctum/csrf-cookie endpoint.
 */
function csrfHeaders(): HeadersInit {
    const token = decodeURIComponent(
        document.cookie
            .split('; ')
            .find((row) => row.startsWith('XSRF-TOKEN='))
            ?.split('=')[1] ?? '',
    );

    return {
        Accept: 'application/json',
        'Content-Type': 'application/json',
        'X-Requested-With': 'XMLHttpRequest',
        ...(token ? { 'X-XSRF-TOKEN': token } : {}),
    };
}

/**
 * Make sure Laravel has initialized the Sanctum CSRF cookie.
 *
 * We only need to do this once before making state-changing API requests.
 */
async function initializeCsrf(): Promise<void> {
    const response = await fetch('/sanctum/csrf-cookie', {
        method: 'GET',
        credentials: 'include',
        headers: {
            Accept: 'application/json',
            'X-Requested-With': 'XMLHttpRequest',
        },
    });

    if (!response.ok) {
        throw new Error('Could not initialize CSRF protection.');
    }
}

/**
 * Parse Laravel's JSON response and throw a useful error when necessary.
 */
async function readJson<T>(response: Response): Promise<T> {
    const data = (await response.json().catch(() => null)) as
        | (T & {
              message?: string;
              errors?: Record<string, string[]>;
          })
        | null;

    if (!response.ok) {
        throw new ApiError(
            data?.message || 'Something went wrong. Please try again.',
            response.status,
        );
    }

    if (data === null) {
        throw new Error('Something went wrong. Please try again.');
    }

    return data;
}

/**
 * Get all conversations belonging to the authenticated user.
 */
export async function getConversations(): Promise<Conversation[]> {
    const response = await fetch(
        ConversationController.index.url(),
        {
            method: 'GET',
            credentials: 'include',
            headers: {
                Accept: 'application/json',
                'X-Requested-With': 'XMLHttpRequest',
            },
        },
    );

    return readJson<Conversation[]>(response);
}

/**
 * Create a new conversation.
 */
export async function createConversation(
    level: ConversationLevel,
    topicId?: number,
): Promise<Conversation> {
    await initializeCsrf();

    const response = await fetch(
        ConversationController.store.url(),
        {
            method: 'POST',
            credentials: 'include',
            headers: csrfHeaders(),
            body: JSON.stringify({
                language: 'es',
                level,
                ...(topicId !== undefined ? { topic_id: topicId } : {}),
            }),
        },
    );

    return readJson<Conversation>(response);
}

/**
 * Get one conversation with its messages and mistakes.
 */
export async function getConversation(
    conversationId: number,
): Promise<ConversationWithMessages> {
    const response = await fetch(
        ConversationController.show.url(conversationId),
        {
            method: 'GET',
            credentials: 'include',
            headers: {
                Accept: 'application/json',
                'X-Requested-With': 'XMLHttpRequest',
            },
        },
    );

    return readJson<ConversationWithMessages>(response);
}

/**
 * Send a message to the Spanish tutor.
 */
export async function sendConversationMessage(
    conversationId: number,
    content: string,
): Promise<SendMessageResponse> {
    await initializeCsrf();

    const response = await fetch(
        ConversationMessageController.store.url(conversationId),
        {
            method: 'POST',
            credentials: 'include',
            headers: csrfHeaders(),
            body: JSON.stringify({
                content,
            }),
        },
    );

    return readJson<SendMessageResponse>(response);
}

export async function deleteConversation(id: number): Promise<void> {
    const response = await fetch(`/api/conversations/${id}`, {
        method: 'DELETE',
        headers: {
            Accept: 'application/json',
        },
        credentials: 'include',
    });

    if (!response.ok) {
        throw new Error('Failed to delete conversation');
    }
}

export type DashboardStats = {
    conversations_count: number;
    mistakes_count: number;
    messages_count: number;
};

export async function getDashboardStats(): Promise<DashboardStats> {
    const response = await fetch('/api/dashboard', {
        method: 'GET',
        credentials: 'include',
        headers: {
            Accept: 'application/json',
            'X-Requested-With': 'XMLHttpRequest',
        },
    });

    return readJson<DashboardStats>(response);
}

export type Topic = {
    id: number;
    title: string;
    slug: string;
    description: string;
    level: ConversationLevel;
    scenario: string;
    vocabulary: string[];
};

export async function getTopics(
    level?: ConversationLevel,
): Promise<Topic[]> {
    const url = new URL('/api/topics', window.location.origin);

    if (level) {
        url.searchParams.set('level', level);
    }

    const response = await fetch(url, {
        method: 'GET',
        credentials: 'include',
        headers: {
            Accept: 'application/json',
            'X-Requested-With': 'XMLHttpRequest',
        },
    });

    const data = await readJson<{ data: Topic[] }>(response);

    return data.data;
}

export async function getTopic(slug: string): Promise<Topic> {
    const response = await fetch(`/api/topics/${encodeURIComponent(slug)}`, {
        method: 'GET',
        credentials: 'include',
        headers: {
            Accept: 'application/json',
            'X-Requested-With': 'XMLHttpRequest',
        },
    });

    const data = await readJson<{ data: Topic }>(response);

    return data.data;
}